name: CI
on:
  push:
    branches:  main 
  pull_request:
    branches:  main 
  workflow_dispatch:
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Run a script that displays name and surname
        run: echo "Dubyniak Oleksandr"
        
      - name: Run a script with file
        run: sh ./task1.sh
